In [3]:
import numpy as np
import pandas as pd

Creating Data Frames

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [6]:
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [9]:
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [13]:
cols = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns=cols)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and Indexing of Columns

Coloumn Selection

In [15]:
df2 ["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [16]:
df2[["Name", "City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Column Insertion

In [23]:
df2["Designation"] = ['Engineer', 'Manager', 'Analyst', 'Director']
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000     Manager
2  Peter   29    Berlin   62000     Analyst
3  Linda   42    London   85000    Director

In [24]:
df2.drop("Designation", axis=1) # This will return a new DataFrame without the "Designation" column, but it won't modify df2 unless you set inplace=True.

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Coloumn removal

In [27]:
df2.drop("Designation", axis=1, inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
df2.drop(["Age", "Salary"], axis=1)

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [29]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selecting Rows

In [30]:
df2.loc[0]  # Access the first row by label (index 0)

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [31]:
df2.loc[[0, 2]]  # Access the first and third rows by label (index 0 and 2)

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

In [32]:
df2. iloc[0]  # Access the first row by integer position (index 0)

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [33]:
df.loc[[0,1]][["Name", "City"]]

   Name      City
0  John  New York
1  Anna     Paris

Conditional Statement

In [ ]:
df2[df2["Age"] > 30] # Filter rows where Age is greater than 30

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
df2[(df2["Age"] > 30) & (df2["Salary"] > 62000)] #we need to use parentheses to group the conditions when using logical operators like & (and) or | (or) in pandas.

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000