In [1]:
import numpy as np 
import pandas as pd

Loading data

In [5]:
df = pd.read_csv('anime.csv')
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [7]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

Make a coloumn for episode count

In [8]:
def extract_episodes(txt):
    check = False
    data = ""
    for i in txt:
        if i == ")":
            check = False
            return data
        if check == True: 
            data = data + i 
        if i == '(':
            check = True

In [9]:
df['Title'].apply(extract_episodes)

0      64 eps
1      24 eps
2      13 eps
3      51 eps
4      10 eps
5      51 eps
6       1 eps
7     148 eps
8      13 eps
9      13 eps
10      2 eps
11    110 eps
12     13 eps
13     13 eps
14     12 eps
15    201 eps
16      1 eps
17     22 eps
18     24 eps
19     25 eps
20      1 eps
21      1 eps
22      7 eps
23     14 eps
24     74 eps
25      1 eps
26      1 eps
27     12 eps
28      1 eps
29     24 eps
30     23 eps
31     12 eps
32     26 eps
33     13 eps
34     16 eps
35     11 eps
36      1 eps
37     11 eps
38     10 eps
39      1 eps
40     26 eps
41     12 eps
42     75 eps
43     26 eps
44     26 eps
45     24 eps
46     10 eps
47     12 eps
48     12 eps
49      4 eps
Name: Title, dtype: str

In [10]:
df["Episodes"] = df['Title'].apply(extract_episodes)
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

Removing " eps" from Episodes

In [11]:
df['Episodes'] = df['Episodes'].str.replace(" eps", "") 
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

Now episodes data is in string. It can be checked by

In [12]:
type(df['Episodes'][0])

str

converting to int

In [13]:
df['Episodes'] = df['Episodes'].astype(int)

make a new coloumn for time stamp

In [14]:
def extraction_time(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i] == ')':
            for j in range(i+1,i+20):
                data += txt[j]

            return data

In [15]:
df['Total Time'] = df ['Title'].apply(extraction_time)
df.head()

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

Now extracting total no of months 
this was done by the help of gpt

In [16]:
from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_months(period):
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1  # +1 to include the starting month
    except:
        return None

df['Months'] = df['Total Time'].apply(calculate_total_months)
df.head()

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

which anime has highest score

In [17]:
df[df['Score'] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: str

Top five highest scoring anime

In [18]:
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str

High episode count anime

In [19]:
df[df['Episodes'] == df['Episodes'].max()]

,Rank,Title,Score,Episodes,Total Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48